// Copyright (c) 2022 GlassBricks
// SPDX-FileCopyrightText: 2025 GlassBricks
//
// SPDX-License-Identifier: LGPL-3.0-or-later

/** @noResolution */
// This file is generated by the tstlPlugin (in tstlPlugin/plugin.cts) upon every compilation
declare module "last-compile-time" {
  const lastCompileTime: string
  export = lastCompileTime
}
